# Generated by Django 3.2.6 on 2021-09-01 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_app_myapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyApp',
            new_name='App',
        ),
    ]
