# Generated by Django 3.2.6 on 2021-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_backupcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenconfig',
            name='secret_tag',
            field=models.CharField(default='mikutano.go.tz', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
