# Generated by Django 3.2.6 on 2021-09-02 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tokenconfig_secret_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tokenconfig'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='enrollment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tokenconfig'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userenrolled'),
        ),
        migrations.AlterField(
            model_name='userenrolled',
            name='app_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
