# Generated by Django 3.2.6 on 2021-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210902_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenconfig',
            name='algorithm',
            field=models.CharField(default='sha1', max_length=7),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='digits',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='period',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='period_skew',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='token_type',
            field=models.CharField(default='totp', max_length=5),
        ),
    ]
