# Generated by Django 3.2.6 on 2021-09-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210904_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='factory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
