# Generated by Django 3.2.6 on 2021-09-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210904_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='config',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='config',
        ),
    ]
