# Generated by Django 3.2.6 on 2021-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210904_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
