# Generated by Django 3.2.6 on 2021-09-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userenrolled_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenConfig',
        ),
    ]
