# Generated by Django 3.2.6 on 2021-09-16 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_app', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('org_name', models.CharField(max_length=200)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated')),
                ('claim_of_property', models.TextField(help_text='Proof of property, space separated')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=30, null=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_service_applicationrequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
