# Generated by Django 3.2.6 on 2021-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
