# Generated by Django 3.2.6 on 2021-11-16 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user id ')),
                ('user', models.CharField(max_length=256, verbose_name='user')),
                ('request_url', models.CharField(max_length=256, verbose_name='url')),
                ('request_method', models.CharField(max_length=10, verbose_name='http method')),
                ('response_code', models.CharField(max_length=3, verbose_name='response code')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='extra data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='user IP')),
            ],
            options={
                'verbose_name': 'activity log',
            },
        ),
    ]
