# Generated by Django 3.2.6 on 2021-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='user')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Deactivate', 'Deactivate'), ('Activate', 'Activate')], default='Deactivate', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
